version: "3.8"

services:
  postgres:
    container_name: tba-postgres
    image: postgres:12
    restart: always
    ports:
      - "4466:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tba
    volumes:
      - postgres:/var/lib/postgresql/data

  prisma:
    links:
      - postgres
    depends_on:
      - postgres
    container_name: prisma
    ports:
      - "5555:5555"
    build:
      context: packages/backend/prisma
      dockerfile: Dockerfile
    volumes:
      - /app/prisma

  backend:
    container_name: tba-backend
    image: ${DOCKER_REGISTRY-}tba-backend
    build:
      context: packages/backend
      dockerfile: Dockerfile
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: tba
    ports:
      - "4000:4000"

  frontend:
    container_name: tba-frontend
    image: ${DOCKER_REGISTRY-}tba-frontend
    build:
      context: packages/frontend
      dockerfile: Dockerfile
      args:
        CLIENT_SCHEMA: src/graphql/schema.graphql
        GPR_TOKEN: ${GPR_TOKEN}
    ports:
      - "3000:3000"

volumes:
  postgres: ~
