version: "3.4"

services:
  frontend:
    container_name: frontend
    image: ${DOCKER_REGISTRY-}frontend
    build:
      context: packages/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
