version: "3.8"

services:
  frontend:
    container_name: tba-frontend
    image: ${DOCKER_REGISTRY-}tba-frontend
    build:
      context: packages/frontend
      dockerfile: Dockerfile
      args:
        CLIENT_SCHEMA: src/graphql/schema.graphql
        GPR_TOKEN: ${GPR_TOKEN}
    ports:
      - "3000:3000"
